name = "sistem-informasi-ma-api"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
API_KEY = "MADRASAH_KEY_2024"

[[d1_databases]]
binding = "DB"
database_name = "sistem-informasi-ma-db"
database_id = "050d4994-ae64-4912-84d4-299988547451"
