import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../../core/mixins/safe_async_mixin.dart';
import '../../core/utils/context_extensions.dart';
import 'services/finance_service.dart';
import 'models/finance_models.dart';
import '../master_data/services/master_service.dart';
import '../master_data/models/master_models.dart';

class FinanceSppPayment extends StatefulWidget {
  const FinanceSppPayment({super.key});

  @override
  State<FinanceSppPayment> createState() => _FinanceSppPaymentState();
}

class _FinanceSppPaymentState extends State<FinanceSppPayment> with SafeAsync {
  final TextEditingController _searchController = TextEditingController();
  final _financeService = FinanceService();
  final _masterService = MasterService();

  Student? _foundSiswa;
  List<SppRecord> _riwayatSpp = [];
  
  final List<String> _bulanAjaran = [
    'Juli', 'Agustus', 'September', 'Oktober',
    'November', 'Desember', 'Januari', 'Februari',
    'Maret', 'April', 'Mei', 'Juni'
  ];

  @override
  void dispose() {
    _searchController.dispose();
    super.dispose();
  }

  Future<void> _searchSiswa() async {
    final query = _searchController.text.trim();
    if (query.isEmpty) {
      context.showErrorSnackBar('Masukkan NIS atau Nama Siswa terlebih dahulu.');
      return;
    }

    await safeCall(
      context: context,
      action: () async {
        final results = await _masterService.searchStudents(query);
        if (results.isEmpty) {
          _foundSiswa = null;
          _riwayatSpp = [];
          if (mounted) context.showErrorSnackBar('Siswa tidak ditemukan.');
        } else {
          _foundSiswa = results.first;
          await _fetchRiwayatSpp(_foundSiswa!.id);
        }
        setState(() {});
      },
    );
  }

  double _currentSppAmount = 250000;

  Future<void> _fetchRiwayatSpp(String studentId) async {
    final data = await _financeService.fetchSppByStudent(studentId);
    
    // Determine level from classId (e.g., '10-A' -> '10')
    String? level;
    if (_foundSiswa?.classId != null) {
      level = _foundSiswa!.classId!.split('-').first;
    }
    
    final nominal = await _financeService.getSppAmount(level);
    
    setState(() {
      _riwayatSpp = data;
      _currentSppAmount = nominal;
    });
  }

  Future<void> _bayarSpp(String bulan) async {
    if (_foundSiswa == null) return;

    final confirmed = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Konfirmasi Pembayaran', style: TextStyle(fontWeight: FontWeight.bold)),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text('Siswa: ${_foundSiswa!.name}'),
            Text('NIS: ${_foundSiswa!.nis}'),
            Text('Bulan: $bulan'),
            const SizedBox(height: 8),
            Text('Nominal: Rp ${_currentSppAmount.toStringAsFixed(0)}', 
                style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16, color: Colors.green)),
          ],
        ),
        actions: [
          TextButton(onPressed: () => Navigator.pop(context, false), child: const Text('Batal')),
          ElevatedButton(
            onPressed: () => Navigator.pop(context, true),
            style: ElevatedButton.styleFrom(backgroundColor: Colors.green.shade700, foregroundColor: Colors.white),
            child: const Text('Konfirmasi Bayar'),
          ),
        ],
      ),
    );

    if (confirmed != true) return;

    await safeCall(
      context: context,
      successMessage: 'Pembayaran SPP $bulan berhasil dicatat!',
      action: () async {
        final record = SppRecord(
          id: '', // Will be generated by Supabase
          studentId: _foundSiswa!.id,
          amount: _currentSppAmount,
          paidAt: DateTime.now(),
          status: 'lunas',
          month: bulan,
          year: DateTime.now().year.toString(),
        );
        await _financeService.addSppPayment(record);
        await _fetchRiwayatSpp(_foundSiswa!.id);
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(24.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              const Text(
                'Pembayaran SPP Bulanan',
                style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold, color: Color(0xFF2B3674)),
              ),
              const Spacer(),
              if (isLoading)
                const SizedBox(width: 20, height: 20, child: CircularProgressIndicator(strokeWidth: 2)),
            ],
          ),
          const SizedBox(height: 24),

          Container(
            padding: const EdgeInsets.all(24),
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(16),
              boxShadow: [BoxShadow(color: Colors.grey.withOpacity(0.05), blurRadius: 10, offset: const Offset(0, 4))],
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Text('Pilih Siswa / Masukkan NIS',
                    style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold, color: Color(0xFF2B3674))),
                const SizedBox(height: 16),
                Row(
                  children: [
                    Expanded(
                      child: TextField(
                        controller: _searchController,
                        onSubmitted: (_) => _searchSiswa(),
                        decoration: InputDecoration(
                          hintText: 'Ketik Nomor Induk (NIS) atau Nama Lengkap',
                          prefixIcon: const Icon(Icons.search),
                          border: OutlineInputBorder(borderRadius: BorderRadius.circular(8)),
                        ),
                      ),
                    ),
                    const SizedBox(width: 16),
                    ElevatedButton(
                      onPressed: isLoading ? null : _searchSiswa,
                      style: ElevatedButton.styleFrom(
                        backgroundColor: Colors.blue.shade700,
                        foregroundColor: Colors.white,
                        padding: const EdgeInsets.symmetric(vertical: 20, horizontal: 32),
                      ),
                      child: const Text('Cari'),
                    ),
                  ],
                ),
              ],
            ),
          ),
          const SizedBox(height: 24),

          if (_foundSiswa != null) _buildSiswaCard(),

          if (_foundSiswa == null && !isLoading)
            Center(
              child: Padding(
                padding: const EdgeInsets.all(40.0),
                child: Column(
                  children: [
                    Icon(Icons.manage_search, size: 64, color: Colors.grey.shade300),
                    const SizedBox(height: 16),
                    const Text('Masukkan NIS atau Nama Siswa untuk mulai'),
                  ],
                ),
              ),
            ),
        ],
      ),
    );
  }

  Widget _buildSiswaCard() {
    final siswa = _foundSiswa!;
    final Set<String> bulanLunas = _riwayatSpp
        .where((p) => p.status == 'lunas')
        .map((p) => p.month ?? '')
        .toSet();

    return Container(
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: Colors.amber.shade400, width: 2),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              const CircleAvatar(child: Icon(Icons.person)),
              const SizedBox(width: 16),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text('${siswa.name} (NIS: ${siswa.nis})',
                        style: const TextStyle(fontSize: 16, fontWeight: FontWeight.bold)),
                    Text('Status: ${siswa.isActive ? "Aktif" : "Non-Aktif"}'),
                  ],
                ),
              ),
            ],
          ),
          const Divider(height: 32),
          Text('${bulanLunas.length} dari ${_bulanAjaran.length} bulan sudah lunas',
              style: const TextStyle(fontWeight: FontWeight.bold)),
          const SizedBox(height: 16),
          SingleChildScrollView(
            scrollDirection: Axis.horizontal,
            child: DataTable(
              columns: const [
                DataColumn(label: Text('Bulan')),
                DataColumn(label: Text('Status')),
                DataColumn(label: Text('Tanggal Bayar')),
                DataColumn(label: Text('Aksi')),
              ],
              rows: _bulanAjaran.map((bulan) {
                final isPaid = bulanLunas.contains(bulan);
                final pembayaran = _riwayatSpp.firstWhere(
                  (p) => p.month == bulan && p.status == 'lunas',
                  orElse: () => SppRecord(id: '', studentId: '', amount: 0, paidAt: DateTime.now(), status: ''),
                );

                return DataRow(
                  cells: [
                    DataCell(Text(bulan)),
                    DataCell(Text(isPaid ? 'Lunas' : 'Belum Lunas',
                        style: TextStyle(color: isPaid ? Colors.green : Colors.red))),
                    DataCell(Text(isPaid ? _formatDate(pembayaran.paidAt) : '-')),
                    DataCell(
                      isPaid
                          ? const Icon(Icons.check_circle, color: Colors.green)
                          : ElevatedButton(
                              onPressed: isLoading ? null : () => _bayarSpp(bulan),
                              child: const Text('Bayar'),
                            ),
                    ),
                  ],
                );
              }).toList(),
            ),
          ),
        ],
      ),
    );
  }

  String _formatDate(DateTime date) {
    return '${date.day}-${date.month}-${date.year}';
  }
}

